// AUTHORIZATION
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ON_START = 'ON_START'
export const ON_END = 'ON_END'

// STUDENTS
export const GET_STUDENT_DATA_START = 'GET_STUDENT_DATA_START'
export const GET_STUDENT_DATA_END = 'GET_STUDENT_DATA_END'
export const GET_STUDENT_DATA = 'GET_STUDENT_DATA'

// PROGRAMS
export const GET_PROGRAM_START = 'GET_PROGRAM_START'
export const GET_PROGRAM_END = 'GET_PROGRAM_END'
export const GET_PROGRAM = 'GET_PROGRAM'

// CITY
export const GET_CITY_START = 'GET_CITY_START'
export const GET_CITY_END = 'GET_CITY_END'
export const GET_CITY = 'GET_CITY'